In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
# Read datasets
data = pd.read_csv('./InflationIndicator_pro.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10023 entries, 0 to 10022
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   year              10023 non-null  int64  
 1   month             10023 non-null  int64  
 2   day               10023 non-null  int64  
 3   USD_EUR_value     10023 non-null  int64  
 4   USD_EGP           10023 non-null  float64
 5   EUR_EGP           10022 non-null  float64
 6   cpi_rate          10023 non-null  float64
 7   cpi_base_2010     10023 non-null  float64
 8   RealInterestRate  10023 non-null  float64
 9   InterestRate      10023 non-null  float64
 10  XAU_Price         10023 non-null  float64
 11  gdp_rate          10023 non-null  float64
dtypes: float64(8), int64(4)
memory usage: 939.8 KB


In [2]:
from sklearn.tree import DecisionTreeRegressor


target_features = ["RealInterestRate","XAU_Price","gdp_rate","USD_EGP"]
target = data[target_features]
X = ["year","month","day"]
x = data[X]
train_X, val_X, train_y, val_y = train_test_split(x, target, random_state = 0)
# Define model. Specify a number for random_state to ensure same results each run
melbourne_model = DecisionTreeRegressor(random_state=1)
# Fit model
melbourne_model.fit(x, target)
# get predicted prices on validation data
val_predictions = melbourne_model.predict(val_X)
print(mean_absolute_error(val_y, val_predictions))

1.1805002074656983e-07


In [3]:
print(melbourne_model.predict(x.tail()))

[[-5.81666667e+00  1.02533850e+05  4.20000000e+00  4.69000000e+01]
 [-5.81666667e+00  1.01756420e+05  4.20000000e+00  4.67500000e+01]
 [-5.81666667e+00  1.00904450e+05  4.20000000e+00  4.67872000e+01]
 [-5.81666667e+00  1.02952660e+05  4.20000000e+00  4.74040000e+01]
 [-5.81666667e+00  1.04194830e+05  4.20000000e+00  4.78222000e+01]]


In [4]:
from sklearn.ensemble import RandomForestRegressor
# split data into training and validation data, for both features and target
# The split is based on a random number generator. Supplying a numeric value to
# the random_state argument guarantees we get the same split every time we
# run this script.
# Define model
melbourne_model = RandomForestRegressor()
# Fit model
melbourne_model.fit(train_X, train_y)

# get predicted prices on validation data
val_predictions = melbourne_model.predict(val_X)
print(mean_absolute_error(val_y, val_predictions))

22.070937969449375


In [5]:
from sklearn.kernel_ridge import KernelRidge

clf = KernelRidge()

clf.fit(train_X, train_y)

val_predictions = clf.predict(val_X)

print(mean_absolute_error(val_y, val_predictions))

2075.4283284527983
